### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by rborn** [Robo-romeski/litstop#1]
Hi,
I'm sorry to bother you but I wonder what were the steps to make the react-native-map work on os with google provider as you did ? 😃 

I tried everything possible in my project and it's not working, it's either not compiling or gives various errors.

Your project runs smooth without any issue.
So it would be amazing of you could tell me what steps you took? (how did you install the module, pods, etc)

Thank you very much in advance 🤗

**Comment by Robo-romeski** [comment]
Here is a great blog post that helped put things in perspective for me - Hope it helps!
https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14

**Comment by rborn** [comment]
ok, thank you so much, I'll give it a try 🤗

**Comment by rborn** [comment]
Managed to do it, but I had to clean watchman, and yarn cache.
Anyway, thanks a lot for your help!
